In [ ]:
import pandas as pd

df = pd.read_csv('seattle-weather.csv')
df

date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [ ]:
# deteksi data null, nan, na, dan duplikasi kemudian hapus

import pandas as pd

df = pd.read_csv('seattle-weather.csv')

# Deteksi data null, NaN, dan NA
print("Jumlah data null, NaN, dan NA:")
print(df.isnull().sum())

# Deteksi duplikasi
print("\nJumlah data duplikat:")
print(df.duplicated().sum())

# Hapus data null, NaN, dan NA
df.dropna(inplace=True)

# Hapus data duplikat
df.drop_duplicates(inplace=True)

print("\nData setelah dihapus:")
df

Jumlah data null, NaN, dan NA:
date             0
precipitation    0
temp_max         0
temp_min         0
wind             0
weather          0
dtype: int64

Jumlah data duplikat:
0

Data setelah dihapus:


date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   date           1461 non-null   object 
 1   precipitation  1461 non-null   float64
 2   temp_max       1461 non-null   float64
 3   temp_min       1461 non-null   float64
 4   wind           1461 non-null   float64
 5   weather        1461 non-null   object 
dtypes: float64(4), object(2)
memory usage: 68.6+ KB


In [ ]:
# code label encoder untuk merubah menjadi angka kolom date dan weather

from sklearn.preprocessing import LabelEncoder

# Inisialisasi LabelEncoder
le = LabelEncoder()

# Ubah kolom 'date' menjadi angka
df['date_encoded'] = le.fit_transform(df['date'])

# Ubah kolom 'weather' menjadi angka
df['weather_encoded'] = le.fit_transform(df['weather'])

print(df[['date', 'date_encoded', 'weather', 'weather_encoded']])

            date  date_encoded  weather  weather_encoded
0     2012-01-01             0  drizzle                0
1     2012-01-02             1     rain                2
2     2012-01-03             2     rain                2
3     2012-01-04             3     rain                2
4     2012-01-05             4     rain                2
...          ...           ...      ...              ...
1456  2015-12-27          1456     rain                2
1457  2015-12-28          1457     rain                2
1458  2015-12-29          1458      fog                1
1459  2015-12-30          1459      sun                4
1460  2015-12-31          1460      sun                4

[1461 rows x 4 columns]


In [ ]:
# tampilkan kolom weather dan weather_encoded tetapi tidak ada duplikasi

print(df[['weather', 'weather_encoded']].drop_duplicates())

     weather  weather_encoded
0    drizzle                0
1       rain                2
7        sun                4
13      snow                3
192      fog                1


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1461 entries, 0 to 1460
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   date             1461 non-null   object 
 1   precipitation    1461 non-null   float64
 2   temp_max         1461 non-null   float64
 3   temp_min         1461 non-null   float64
 4   wind             1461 non-null   float64
 5   weather          1461 non-null   object 
 6   date_encoded     1461 non-null   int64  
 7   weather_encoded  1461 non-null   int64  
dtypes: float64(4), int64(2), object(2)
memory usage: 91.4+ KB


In [ ]:
import numpy as np

x_train = np.array(df[['precipitation', 'temp_max', 'temp_min', 'wind']]) # konversi data menjadi np.array dan ditampung ke variable x_train sebagai sekumpulan features untuk training set
y_train = np.array(df['weather_encoded'])                                 # konversi data menjadi np.array dan ditampung ke variable y_train sebagai sekumpulan nilai target untuk training set

print(f'x_train:\n{x_train}\n')
print(f'y_train: {y_train}')

x_train:
[[ 0.  12.8  5.   4.7]
 [10.9 10.6  2.8  4.5]
 [ 0.8 11.7  7.2  2.3]
 ...
 [ 0.   7.2  0.6  2.6]
 [ 0.   5.6 -1.   3.4]
 [ 0.   5.6 -2.1  3.5]]

y_train: [0 2 2 ... 1 4 4]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier

K = 6
model = KNeighborsClassifier(n_neighbors = K)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=6)

In [ ]:
# melakukan prediksi cuaca dengan precipitation, temp_max, temp_min, dan wind
precipitation = 1.9
temp_max = 15.5
temp_min = 0.1
wind = 2.7
x_new = np.array([precipitation, temp_max, temp_min, wind])
x_new


array([ 1.9, 15.5,  0.1,  2.7])

In [ ]:
# prediksi cuaca dengan model KNeighborsClassifier yang sudah di training
y_new = model.predict([x_new])
y_new

array([4])

In [ ]:
# panggil kembali label encoder untuk mengingatkan nomer 4 itu cuaca apa
le.inverse_transform(y_new)

array(['sun'], dtype=object)

In [ ]:
# bentuk data menjadi np.array dan tampung ke varialble misterius
misterius = np.array([precipitation, temp_max, temp_min, wind])
misterius

array([ 1.9, 15.5,  0.1,  2.7])

In [ ]:
#tampilkan sekumpulan nilai features dari training set
x_train

array([[ 0. , 12.8,  5. ,  4.7],
       [10.9, 10.6,  2.8,  4.5],
       [ 0.8, 11.7,  7.2,  2.3],
       ...,
       [ 0. ,  7.2,  0.6,  2.6],
       [ 0. ,  5.6, -1. ,  3.4],
       [ 0. ,  5.6, -2.1,  3.5]])

In [ ]:
#kalkulasi jarak antara data file misterius dengan data file lain di dalam data file x_train
from scipy.spatial.distance import euclidean

data_jarak = [euclidean(misterius, d) for d in x_train]
data_jarak

[6.237788069500278,
 10.748953437428222,
 8.137567204023572,
 19.588261791185047,
 7.922752047110902,
 11.323868596906271,
 8.941476388158726,
 6.452906321960671,
 8.214012417813843,
 9.482088377567464,
 9.958413528268446,
 9.790301323248432,
 11.145851246091524,
 11.6215317406958,
 15.189799208679489,
 14.300349646075093,
 13.989281611290837,
 23.965808978626196,
 21.49581354589772,
 14.319567032560727,
 9.671607932500159,
 10.193134944657606,
 7.567033764957045,
 9.236341266973627,
 10.381714694596456,
 7.57495874576225,
 9.382430388763884,
 9.030503861911583,
 26.842689880114474,
 9.822932352408825,
 8.640601830891178,
 13.72443077143821,
 7.617086057016817,
 3.9987498046264407,
 5.494542747126461,
 2.961418578992169,
 3.438022687534217,
 8.283718971573094,
 7.420916385460761,
 8.893818077743664,
 7.162401831787993,
 8.689649014776142,
 8.866791979064356,
 13.39104178172856,
 8.885943956609225,
 8.576712656956628,
 8.916277250063505,
 16.923061188803874,
 11.886547017532047,
 9.4583

In [ ]:
# membentuk kolom baru dengan nama jarak yang datanya diambil dari variable data_jarak dan di urutkan dar nilai terkecil hingga nilai terbesar
df['jarak'] = data_jarak
df.sort_values('jarak')

date  precipitation  temp_max  temp_min  wind weather  \
67    2012-03-08            0.0      15.6       0.6   2.5     sun   
35    2012-02-05            0.0      13.9       1.7   2.9     sun   
97    2012-04-07            0.0      16.1       1.7   4.3     sun   
820   2014-03-31            0.0      15.6       2.2   3.8     sun   
428   2013-03-04            0.0      13.3       0.0   3.9     sun   
...          ...            ...       ...       ...   ...     ...   
794   2014-03-05           46.7      15.6      10.6   3.9    rain   
1413  2015-11-14           47.2       9.4       6.1   4.5    rain   
323   2012-11-19           54.1      13.3       8.3   6.0    rain   
1437  2015-12-08           54.1      15.6      10.0   6.2    rain   
1169  2015-03-15           55.9      10.6       6.1   4.2    rain   

      date_encoded  weather_encoded      jarak  
67              67                4   1.977372  
35              35                4   2.961419  
97              97                4   3.014963  
820            820                4   3.039737  
428            428                4   3.146427  
...            ...              ...        ...  
794            794                2  46.029773  
1413          1413                2  46.136103  
323            323                2  52.988772  
1437          1437                2  53.245751  
1169          1169                2  54.573437  

[1461 rows x 9 columns]

In [ ]:
#testing set
x_test = np.array([[1.9, 15.5, 0.1, 2.7], [3.7, 10.7, 2.0, 3.0], [1.7, 14.7, 0.0, 5.0], [34.7, 9.7, -1.0, 6.0]]) # menyiapkan features untuk target
y_test = le.transform(['sun', 'fog', 'sun', 'sun'])                                                              # menyiapkan target yang sudah di ubah menjadi numeric biner dengan label encoder

print(f'x_test:\n{x_test}\n')
print(f'y_test: {y_test}')


x_test:
[[ 1.9 15.5  0.1  2.7]
 [ 3.7 10.7  2.   3. ]
 [ 1.7 14.7  0.   5. ]
 [34.7  9.7 -1.   6. ]]

y_test: [4 1 4 4]


In [ ]:
#prediksi terhadap testing set
y_pred = model.predict(x_test)
y_pred

array([4, 2, 4, 2])

In [ ]:
#akurasi
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test, y_pred)        # panggil accuracy score dan menyertakan 2 parameter yaitu y_test yang merupakn target dari testing set, dan y_pred merupakan hasil prediksi hasil dari testing set
print(f'Akurasi: {acc}')

Akurasi: 0.5


In [ ]:
#presisi merupakan proporsi dari testing set yang diprediksi sebagai positif oleh model dan benar benar positif
from sklearn.metrics import precision_score

prec = precision_score(y_test, y_pred, average='weighted')     # panggil precision score dan menyertakan 2 parameter yaitu y_test yang merupakn target dari testing set, dan y_pred merupakan hasil prediksi hasil dari testing set. Lalu juga memanggil average "weighted" yang digunakan untuk menghitung rata-rata dari sekumpulan data.
print(f'Presisi: {prec}')

Presisi: 0.75


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
#recall adalah proporsi dari testing set yang benar benar positif, yang diprediksi sebagai positif oleh model
from sklearn.metrics import recall_score

rec = recall_score(y_test, y_pred, average='weighted')    # panggil recall score dan menyertakan 2 parameter yaitu y_test yang merupakn target dari testing set, dan y_pred merupakan hasil prediksi hasil dari testing set. Lalu juga memanggil average "weighted" yang digunakan untuk menghitung rata-rata dari sekumpulan data.
print(f'Recall: {rec}')

Recall: 0.5


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [ ]:
#F1 score adalah nilai rata rata harmonic dari precision dan recall
from sklearn.metrics import f1_score

f1 = f1_score(y_test, y_pred, average='weighted')     # panggil f1 score dan menyertakan 2 parameter yaitu y_test yang merupakn target dari testing set, dan y_pred merupakan hasil prediksi hasil dari testing set. Lalu juga memanggil average "weighted" yang digunakan untuk menghitung rata-rata dari sekumpulan data
print(f'F1 score: {f1}')

F1 score: 0.6000000000000001


In [ ]:
#classification report
from sklearn.metrics import classification_report
cls_report = classification_report(y_test, y_pred)        # panggil classification report dan menyertakan 2 parameter yaitu y_test yang merupakn target dari testing set, dan y_pred merupakan hasil prediksi hasil dari testing set.Lalu ditampung ke variable cls_report
print(f'Classification Report:\n{cls_report}')

Classification Report:
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         1
           2       0.00      0.00      0.00         0
           4       1.00      0.67      0.80         3

    accuracy                           0.50         4
   macro avg       0.33      0.22      0.27         4
weighted avg       0.75      0.50      0.60         4



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_

In [ ]:
#matthews correlation coefficient (mcc) adalah alternatif untuk f1 score sebagai keperluan pengukuran performa dari binary classifiers
from sklearn.metrics import matthews_corrcoef
mcc = matthews_corrcoef(y_test, y_pred)           # panggil matthews corrcoef dan menyertakan 2 parameter yaitu y_test yang merupakn target dari testing set, dan y_pred merupakan hasil prediksi hasil dari testing set.Lalu ditampung ke variable mcc
print(f'MCC: {mcc}')

MCC: 0.2886751345948129
